name: Build on Ubuntu

on:
  push:
    branches:
      - master
      - main
      - v*

    tags:
      - v*

    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt

  pull_request:
    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: >
          sudo apt-get update && sudo apt-get install -y
          cmake build-essential libluajit-5.1-dev libmysqlclient-dev
          libboost-date-time-dev libboost-system-dev libboost-iostreams-dev libboost-filesystem-dev
          libpugixml-dev libfmt-dev libssl-dev

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DUSE_LUAJIT=ON
        env:
          CC: gcc
          CXX: g++

      - name: Build
        run: cmake --build build -j$(nproc)

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-tfs-amd64-${{ github.sha }}
          path: build/tfs
